/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void printResult(int age, int size) {
    Calculate calc = new Calculate();
    int individual = calc.getIndividualFee(age);
    int total = calc.getTotalFee(age, size);

    if (size >= 10) {
      System.out
          .println(
              "Age " + age + ", Size " + size + ": " + "Individual " + individual + ", Total " + total
                  + " (Discount applied).");
    } else {
      System.out
          .println(
              "Age " + age + ", Size " + size + ": " + "Individual " + individual + ", Total " + total
                  + ".");
    }
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    printResult(12, 9);
    printResult(13, 10);
  }
}
